stages:
  Download Catalog:
    cmd: python -m zipf_law.scripts.download_catalog
    deps:
    - .\zipf_law\scripts\download_catalog.py
    outs:
    - .\data\raw\catalog.tar.bz2
  Process Catalog:
    cmd: python -m zipf_law.scripts.process_catalog
    deps:
    - .\data\raw\catalog.tar.bz2
    - .\zipf_law\scripts\process_catalog.py
    outs:
    - .\data\processed\catalog.csv
  Download Dataset:
    cmd: python -m zipf_law.scripts.download_books
    deps:
    - .\data\processed\catalog.csv
    - .\zipf_law\scripts\download_books.py
    - config.ini
    outs:
    - .\data\raw\books\
  Preprocess Books:
    cmd: python -m zipf_law.scripts.preprocess ./data/raw/books/ 
      ./data/processed/books/
    deps:
    - .\data\raw\books\
    - .\zipf_law\scripts\preprocess.py
    outs:
    - .\data\processed\books\
